spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog.xml